### PR TITLE
feat(*) : Add support for passing kube config path and kube context

### LINKED ISSUE #106: --kube-context parameter not respected
Just ran into this bug. Turns out you need to set your default context to the one you're interested in, because the plugin ignores the `--kube-context` parameter (which is a global param on the `helm` CLI). 

This is actually kinda dangerous (more so than #11) because you could easily accidentally interact with the wrong cluster and screw things up, thinking your normal global Helm parameters work as expected. Thankfully, I was just messing with a dev environment when I bumped into this.

### PR DESCRIPTION
**Pull request by hickeyma**
The plugin uses [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) to access the cluster. Currently, the plugin depends on the ` KUBECONFIG` env variable and the context to be set.

This PR expands this by allowing the plugin user to set the kubeconfig file and the context.

closes #106

### CODE REVIEW

**Comment by hickeyma** [comment]
Thanks for the review @bacongobbler

**Comment by marckhouzam** [comment]
@hickeyma I can't get the --kube-context flag to work for me.  When I call:
```
helm 2to3 convert --kube-context lab myrelease
```
The `kube-context` seems to be ignored.
I looked a bit into the code and here is my impression of what is happening.

The `--kube-context` flag is being swallowed by helm and never reaches the plugin.  This is expected behaviour for helm global flags (see https://helm.sh/docs/topics/plugins/#a-note-on-flag-parsing).  

I think the plugin should instead read the `HELM_KUBECONTEXT` variable to figure out if the user has specified a context on the command-line.  This also implies the plugin should not have its own `--kube-context` flag but rely on helm's global one.

What do you think?

**Comment by hickeyma** [comment]
@marckhouzam Can you open an issue to handle and track the issue?

**Comment by marckhouzam** [comment]
> @marckhouzam Can you open an issue to handle and track the issue?

Done.  #128

**Pull request merged**
