### PR TITLE
chore(Readme): replaced grep|cut|uniq with awk

### PR DESCRIPTION
**Pull request by itninja-hue**
a small improvement

### CODE REVIEW

**Comment by hickeyma** [comment]
ping @itninja-hue ^^

**Comment by itninja-hue** [comment]
@hickeyma replaced what is done by grep ; cut; uniq by one awk script. it looks more elegant and surly its more effective.

**Comment by rimusz** [comment]
@itninja-hue thank you for the PR.
Looking to the change I do not really see a big value of the change, it makes more difficult to understand the command and users which are less familiar with `awk` will get lost there.

**Comment by itninja-hue** [comment]
@rimusz  @hickeyma  thank you for your reviews, and @rimusz i get your perspective and i agree.

**Comment by rimusz** [comment]
@itninja-hue thanks for understanding it 👍

**Pull request closed without merging**
