### PR TITLE
fix(typo): Fix "respoitories" typos in README

### PR DESCRIPTION
**Pull request by macsual**
"respoitories" -> "repositories"

### CODE REVIEW

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @macsual

**Comment by hickeyma** [comment]
@macsual Can you sign the DCO? You will find details in [Helm DCO](https://helm.sh/blog/helm-dco/) blog.

**Comment by hickeyma** [comment]
Ping @macsual

**Comment by macsual** [comment]
> @macsual Can you sign the DCO? You will find details in [Helm DCO](https://helm.sh/blog/helm-dco/) blog.

Hi, I'll try to do this today.

**Comment by rimusz** [comment]
Ping @macsual

**Comment by hickeyma** [comment]
Closing this as no response since January.  We can re-open if need be.

**Pull request closed without merging**
